nome = str(input('Digite seu nome completo: ')).strip()
r1 = nome.split()
print('\033[30;44mMuito prazer em te conhecer!\033[m')
print('O seu primeiro nome é {}'.format(r1[0]))
print('Seu último nome é {}'.format(nome[len(nome)-1]))
